version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tonkatekAdmin
      MYSQL_DATABASE: tonkatek_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/bbdd.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - tfg_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: tonkatekAdmin
    ports:
      - "8080:80"
    networks:
      - tfg_network

  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: apache_php_server
    restart: always
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    networks:
      - tfg_network

  tailwind:  # ‚Üê Debe estar al mismo nivel que db, phpmyadmin, web
    build:
      context: ./tailwind
      dockerfile: Dockerfile
    container_name: tailwind_watcher
    restart: always
    volumes:
      - ./src:/app/src:rw
      - ./tailwind/tailwind.config.js:/app/tailwind.config.js:ro
    working_dir: /app
    command: sh -c "npm run build && npm run watch"
    stdin_open: true
    tty: true
    networks:
      - tfg_network

networks:
  tfg_network:
    driver: bridge